spring.profiles.active: dev
spring.application:
    name: "@project.name@" #从pom.xml中获取

server.port: 8082

logging:
  config: classpath:logback-spring.xml
  level:
    root: info # 总的日志级别,会覆盖logback中的root级别
    #com.reven.controller: info # 指定包的日志级别

spring.mvc:
  view.suffix: .html  # 给返回的页面添加后缀名
  view.prefix: classpath:/templates/  # 定位模板的目录
  static-path-pattern: /static/** # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  


# 数据库配置
deploy.datasource:
  ip: localhost
  dbname: test
  username: root
  password: 123456

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${deploy.datasource.ip}:3306/${deploy.datasource.dbname}?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: ${deploy.datasource.username}
  password: ${deploy.datasource.password}
    

# 公共配置与profiles选择无关
mybatis:
# mybatis日志打印设置
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*Mapper.xml,classpath*:sqlmap/*Mapper.xml
